title: "Tech with Thiru"
description: "Full Stack Architect | Azure & Cloud Solutions | Driving Legacy Modernization & DevOps | API Strategy & Governance"
baseurl: "/resume" 
url: "https://techwiththiru.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
