name: Build Resume PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PDF_NAME: "thiru-resume.pdf"

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF from index.html
        run: |
          wkhtmltopdf --encoding utf-8 --enable-local-file-access \
          _site/index.html "${{ env.PDF_NAME }}"

      # - name: Upload PDF as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: resume-pdf
      #     path: "${{ env.PDF_NAME }}"

      # - name: Upload to GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: "${{ env.PDF_NAME }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move PDF to docs/
        run: |
          FILE=${{ env.PDF_NAME }}
          rm -f "docs/$FILE"
          mv "$FILE" docs/

